-- AMS Major Courses
INSERT INTO Courses(subject, crs, title) VALUES ("AMS", 102, "Elements of Statistics"),
	("AMS", 151, "Applied Calculus I"),("AMS", 161, "Applied Calculus II"),("AMS", 210, "Applied Linear Algebra"),
	("AMS", 261, "Applied Calculus III"), ("AMS", 300, "Writing (and Speaking) in Applied Mathematics"),
	("AMS", 301, "Finite Mathematical Structures"),("AMS", 303, "Graph Theory"),("AMS", 310, "Survey of probability and Stat"),
	("AMS", 311, "Probability Theory"),("AMS", 312, "Mathematical Statistics"),("AMS", 315, "Data Analysis"),
	("AMS", 317, "Introduction to Linear Regression Analysis"),("AMS", 318, "Financial Mathematics"),
	("AMS", 326, "Numerical Analysis"),("AMS", 361, "Applied Calculus IV"),("AMS", 394, "Statistical Laboratory"),
	("AMS", 412, "Mathematical Statistics"),("AMS", 475, "Undergrad Teaching Practicum"),
	("AMS", 476, "Undergrad Teaching Practicum"),("AMS", 487, "Research in Applied Mathematic"),
	
	("MAP", 103, "Proficiency Algebra"),("MAT", 122, "Overview of Calculus with Appl"),("MAT", 123, "Precalculus"),
	("MAT", 125, "Calculus A"),("MAT", 126, "Calculus B"),("MAT", 127, "Calculus C"),("MAT", 131, "Calculus I"),
	("MAT", 132, "Calculus II"),("MAT", 141, "Analysis I"),("MAT", 142, "Analysis II"),
	("MAT", 171, "Accelerated Single-Variable Calculus"),("MAT", 200, "Logic, Language, and Proof"),
	("MAT", 211, "Introduction to Linear Algebra"),("ACC", 210, "Financial Accounting"),
	("BUS", 115, "Introduction to Business"),("BUS", 215, "Intro to Business Statistics"),
	("BUS", 220, "Intro to Decision Science"),("BUS", 301, "Business Communications"),
	("BUS", 302, "Social Media Marketing"),("BUS", 330, "Principles of Finance"),("BUS", 332, "Entrepreneurial Finance"),
	("BUS", 346, "Operations Management"),("BUS", 348, "Principles of Marketing"),("BUS", 353, "Entrepreneurship"),
	("BUS", 355, "Investment Analysis"),("BUS", 358, "Marketing Research"),("BUS", 365, "Financial Management"),
	("BUS", 448, "Marketing Strategy"),("BUS", 475, "Undergrad Teaching Practicum I"),("BUS", 488, "Leadership"),
	("BUS", 331, "International Finance"),("BUS", 333, "Introduction to the Business of Real Esate"),
	("BUS", 336, "Mergers and Acquisitions"),("BUS", 356, "Financial Engineering"),("BUS", 366, "Money and Financial Institutions"),
	("BUS", 468, "Risk Arbitrage"),("BUS", 334, "Consumer Advertising and Promotion"),("BUS", 357, "Principles of Sales"),
	("BUS", 359, "Consumer Behavior"),("BUS", 361, "Retail Management"),("BUS", 362, "Principles of International Marketing"),
	("BUS", 363, "Brand Management"),("BUS", 369, "Marketing of New Products"),("BUS", 449, "Marketing Client Project"),
	("BUS", 340, "Information Systems in Management"),("BUS", 370, "Lean Practices in Operations"),
	("BUS", 371, "Supply Chain Management"),("BUS", 372, "Quality Managemnt"),("BUS", 393, "Principles of Project Management"),
	
	("ACC", 214, "Managerial Cost Analysis and Applicatioins"),("ACC", 310, "Intermediate Accounting I"),
	("ACC", 311, "Federal Income Taxation I"),("ACC", 313, "Intermediate Accounting II"),("ACC", 314, "Federal Income Taxation II"),
	("ACC", 315, "Accounting for the Small Business Entrepreneur"),("ACC", 400, "External Auditing"),
	
	("CSE", 101, "Introduction to Computers"),("CSE", 102, "Intro to Web Design & Programming"),
	("CSE", 114, "Intro to Object-Oriented Prog"),("CSE", 130, "Intro to C Programming"),("CSE", 214, "Data Structure"),
	("CSE", 215, "Foundations of Comp Science"),("CSE", 216, "Programming Abstractions"),("CSE", 219, "Computer Science III"),
	("CSE", 220, "System Fundamentals I"),("CSE", 300, "Technical Communications"),("CSE", 303, "Introduction to Theory of Computation"),
	("CSE", 304, "Compiler Design"),("CSE", 305, "Principles of Database System"),("CSE", 306, "Operating Systems"),
	("CSE", 307, "Principles of Programming Language"),("CSE", 308, "Software Engineerinp"),("CSE", 310, "Computer Networks"),
	("CSE", 312, "Legal, Social, and Ethical Issues in Info System"),("CSE", 316, "Fundamentals of Software Development"),
	("CSE", 320, "System Fundamentals II"),("CSE", 327, "Fundamentals of Computer Vision"),
	("CSE", 328, "Fundamentals of Computer Graphics"),("CSE", 346, "Computer Communications"),
	("CSE", 352, "Aritificial Intelligence"),("CSE", 373, "Analysis of Algorithms"),
	("CSE", 475, "Undergrad Teaching Practicum"),("CSE", 487, "Research Computer Science"),
	
	("EST", 194, "Decision-Making"),("EST", 200, "Cultural Technologies and Society"),
	("EST", 202, "Intro to Sci, Tech, Soc, Studies"),("EST", 204, "Modern Digital Tech Infrastructure"),
	("EST", 205, "Introduction to Technological Design"),("EST", 207, "Interaction Design"),
	("EST", 208, "Virtual Distance Foundations: Collaborating Across Boundaries in the Digital Age"),
	("EST", 230, "ICT for Development"),("EST", 240, "Visual Rhetoric and Information Technology"),
	("EST", 304, "Communication for Engineers"),("EST", 305, "Applications Software for Information Management"),
	("EST", 306, "Cloud Computing Applications"),("EST", 310, "Design of Computer Games"),
	("EST", 320, "Communication Technology Systems"),("EST", 323, "Human Computer Interaction"),
	("EST", 325, "Technology in the Workplace"),("EST", 326, "Management for Engineers"),("EST", 327, "Marketing for Engineers"),
	("EST", 330, "Natural Disasters: Social Impacts and Technological Solutions"),("EST", 331, "Engineering Ethics"),
	("EST", 364, "How to Build a Startup"),("EST", 371, "Data Sci Management"),("EST", 372, "The Mobile Revolution in Development"),
	("EST", 391, "Technology Assesment"),("EST", 392, "Engineering & Managerial Economics"),("EST", 393, "Project Management"),
	("EST", 440, "Interdis Rsch Methods"),("EST", 441, "Interdis Senior Project"),
	("EST", 488, "Internship in Technology & Society"),("EST", 499, "Research in Tech & Society"),
	
	("MEC", 101, "Freshman Design Innovation"),("MEC", 102, "Engineering Computing and Problem Solving"),
	("MEC", 203, "Eng Graphics and CAD"),("MEC", 214, "Probability and Statistics"),
	("MEC", 220, "Practical Electronics Mechanical Engineers"),("MEC", 225, "Fundamentals of Machine Practices"),
	("MEC", 226, "Modern Machine Practices"),("MEC", 260, "Engineering Statics"),("MEC", 262, "Engineering Dynamics"),
	("MEC", 300, "Technical Communication in Mechanical Engineering"),("MEC", 301, "Thermodynamics"),
	("MEC", 305, "Heat and Mass Transfer"),("MEC", 310, "Introduction to Machine Design"),
	("MEC", 316, "Mech Engmg Lab I"),("MEC", 317, "Mech Engmg Lab II"),("MEC", 320, "Num Methods Eng Des Anal"),
	("MEC", 325, "Manufacturing Processes"),("MEC", 363, "Mechanics of Solids"),("MEC", 364, "Intro to Fluid Mechanics"),
	("MEC", 402, "Machine Vibrations"),("MEC", 410, "Design of Machine Elements"),
	("MEC", 411, "Control System Analysis and Design"),("MEC", 422, "Thermal System Design"),
	("MEC", 440, "Mechanical Engnrng Design I"),("MEC", 441, "Mechanical Engnrng Design II"),("MEC", 455, "Applied Stress Analysis"),
	("MEC", 499, "Research in Mechanical Engnrng"),
	
	("CAR", 210, "Career Planning"),("CHI", 111, "Elementary Chinese I"),("CHI", 112, "Elementary Chinese II"),
	("ECO", 108, "Introduction to Economics"),("ECO", 303, "Intermediate Microeconomic Theory"),
	("ECO", 305, "Intermediate Macroeconomic Theory"),("ECO", 321, "Econometrics"),("ECO", 355, "Game Theory"),
	("ECO", 360, "Money and Banking"),("ECO", 383, "Public Finance"),("EST", 102, "Weather and Climate"),
	("EST", 104, "Projects in Technology and Society"),("KOR", 111, "Elementary Korean I"),
	("KOR", 112, "Elementary Korean II"),("KOR", 220, "Intermediate Heritage Korean"),
	("MUS", 105, "Music Cultures of the World"),("POL", 101, "World Politics"),("POL", 102, "Intro to American Government"),
	("SOC", 105, "Introduction to Sociology"),("SUS", 206, "Economics and Sustainability"),
	
	("WAE", 190, "Intermediate Writing"),("WAE", 192, "High Intermediate Writing"),("WAE", 194, "Advanced Writing Academic Eng"),
	("WRT", 101, "Introductory Writing Workshop"),("WRT", 102, "Intermediate Writing Workshop"),
	
	
	("ATM", 102, "Weather and Climate"),("ATM", 205, "Introduction to Atmospheric Sciences"),
	("AST", 203, "Astronomy"),("AST", 205, "Introduction to Planetary Sciences"),
	
	("BIO", 201, "Organisms to Ecosystems"),("BIO", 202, "Molecular and Cellular Biology"),
	("BIO", 203, "Cellular and Organ Physiology"),("BIO", 204, "Fundamentals of Scientific Inquiry in the Biological Sciences I"),
	
	("CHE", 131, "General Chemistry IB"),("CHE", 132, "General Chemistry II"),("CHE", 133, "General Chemistry Lab I"),
	("CHE", 134, "General Chemistry Lab II"),("CHE", 152, "Molecular Science I"),("CHE", 154, "Molecular Science Lab II"),
	("CHE", 321, "Organic Chemistry I"),("CHE", 322, "Organic Chemistry IIA"),("CHE", 331, "Molecular Science II"),
	("CHE", 332, "Molecular Science III"),
	
	("ENS", 101, "Prospects for Planet Earth"),("ESG", 198, "Fundamentals of Engineering Chemistry"),
	("ESG", 281, "Engnrng intro to Solid State"),("ESG", 332, "Materials Sci I: Struct & Prop"),
	
	("GEO", 101, "Environmental Geology"),("GEO", 102, "The Earth"),("GEO", 103, "The Earth Through Time"),
	("GEO", 112, "Physical Geology Laboratory"),("GEO", 113, "Historical Geology Laboratory"),
	("GEO", 122, "Physical Geology"),("GEO", 304, "Energy, Mineral Resources, and the Environment"),
	("GEO", 310, "Introduction to Geophysics"),("GEO", 311, "Geoscience and Global Concerns"),
	("GEO", 312, "Structure and Properties of Materials"),
	
	("MAR", 104, "Oceanography"),
	("PHY", 125, "Classical Physics A"),("PHY", 126, "Classical Physics B"),("PHY", 127, "Classical Physics C"),
	("PHY", 131, "Classical Physics I"),("PHY", 132, "Classical Physics II"),("PHY", 133, "Classical Physics Laboratory I"),
	("PHY", 134, "Classical Physics Lab II"),("PHY", 251, "Modern Physics"),("PHY", 252, "Modern Physics Laboratory"),
	("PSY", 103, "Introduction to Psychology");
